# Generated by Django 2.0.3 on 2018-03-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0002_auto_20180316_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='total_amount',
            new_name='number',
        ),
    ]
